### PR TITLE
.csv file generation

### PR DESCRIPTION
**Pull request by duncanbradley**

### CODE REVIEW

**Comment by ajstewartlang** [comment]
Can you summarise what the changes are please?
—
Dr Andrew J. Stewart
Division of Neuroscience and Experimental Psychology
Zochonis Building
School of Biological Sciences
University of Manchester
Oxford Road
Manchester M13 9PL

Fellow of the Software Sustainability Institute<https://www.software.ac.uk>

Follow me on Twitter
@ajstewart_lang

My academic website<https://ajstewartlang.netlify.com>

Are you an academic at the University of Manchester and interested in open and reproducible research practices? Join our UoM Open Research Working Group mailing list<https://listserv.manchester.ac.uk/cgi-bin/wa?SUBED1=open_research&A=1>

On 11 Feb 2020, at 13:20, duncanbradley <notifications@github.com<mailto:notifications@github.com>> wrote:

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ajstewartlang/Rafia_plots/pull/3

Commit Summary

  *   update
  *   Merge branch 'master' of https://github.com/duncanbradley/Rafia_plots
  *   update

File Changes

  *   A .DS_Store<https://github.com/ajstewartlang/Rafia_plots/pull/3/files#diff-0> (0)
  *   A 20x20grid.png<https://github.com/ajstewartlang/Rafia_plots/pull/3/files#diff-1> (0)
  *   A graphs/.DS_Store<https://github.com/ajstewartlang/Rafia_plots/pull/3/files#diff-2> (0)
  *   M script.R<https://github.com/ajstewartlang/Rafia_plots/pull/3/files#diff-3> (19)
  *   A summary_stats/.DS_Store<https://github.com/ajstewartlang/Rafia_plots/pull/3/files#diff-4> (0)

Patch Links:

  *   https://github.com/ajstewartlang/Rafia_plots/pull/3.patch
  *   https://github.com/ajstewartlang/Rafia_plots/pull/3.diff

**Comment by duncanbradley** [comment]
- Improved description of code for adding extra gridlines
- Added "_s" as a suffix on summary stats files
- Added "_axis" as a suffix on files containing y axis limits
- Updated .csv compilation code to reflect these file names

**Comment by ajstewartlang** [comment]
Ready to send to Rafia?

**Comment by duncanbradley** [comment]
Yes, that's all. Ready to go.

**Pull request merged**
